Galera: update ocf agent

diff --git a/openstack-installer/roles/galera/files/galera-agent b/openstack-installer/roles/galera/files/galera-agent
--- a/openstack-installer/roles/galera/files/galera-agent
+++ b/openstack-installer/roles/galera/files/galera-agent
@@ -61,21 +61,6 @@
 #
 ##
 
-# usage: crm_mon_no_validation args...
-# run crm_mon without any cib schema validation
-# This is useful when an agent runs in a bundle to avoid potential
-# schema validation errors when host and bundle are not perfectly aligned
-# To be used, your shell must support on process substitution (e.g. bash)
-# returns:
-#    <crm_mon error codes>
-
-crm_mon_no_validation()
-{
-        # The subshell prevents parsing error with incompatible shells
-        "$SHELL" -c "CIB_file=<(${HA_SBIN_DIR}/cibadmin -Q | sed 's/validate-with=\"[^\"]*\"/validate-with=\"none\"/') \
-        ${HA_SBIN_DIR}/crm_mon \$*" -- $*
-}
-
 #######################################################################
 # Initialization:
 
@@ -511,9 +496,9 @@ clear_master_score()
 {
     local node=$(ocf_attribute_target $1)
     if [ -z "$node" ]; then
-        $CRM_MASTER -D
+        ocf_promotion_score -D
     else 
-        $CRM_MASTER -D -N $node
+        ocf_promotion_score -D -N $node
     fi
 }
 
@@ -522,9 +507,9 @@ set_master_score()
     local node=$(ocf_attribute_target $1)
 
     if [ -z "$node" ]; then
-        $CRM_MASTER -v 100
+        ocf_promotion_score -v 100
     else 
-        $CRM_MASTER -N $node -v 100
+        ocf_promotion_score -N $node -v 100
     fi
 }
 
@@ -837,6 +822,11 @@ galera_promote()
         return $rc
     fi
 
+    # At this point, the mysql pidfile is created on disk and the
+    # mysql server is reacheable via its UNIX socket. If we are a
+    # joiner, SST transfers (rsync) have finished, but an IST may
+    # still be requested or ongoing
+
     galera_monitor
     rc=$?
     if [ $rc != $OCF_SUCCESS -a $rc != $OCF_RUNNING_MASTER ]; then
@@ -847,12 +837,6 @@ galera_promote()
     is_readonly
     if [ $? -eq 0 ]; then
         ocf_exit_reason "Failure. Master instance started in read-only mode, check configuration."
-        return $OCF_ERR_GENERIC
-    fi
-
-    is_primary
-    if [ $? -ne 0 ]; then
-        ocf_exit_reason "Failure. Master instance started, but is not in Primary mode."
         return $OCF_ERR_GENERIC
     fi
 
@@ -1006,8 +990,18 @@ galera_monitor()
         fi
         rc=$OCF_RUNNING_MASTER
     else
-        ocf_exit_reason "local node <${NODENAME}> is started, but not in primary mode. Unknown state."
-        rc=$OCF_ERR_GENERIC
+        # It seems that with recent galera (26.4+), a joiner that is
+        # connected to a Primary component and is preparing its IST
+        # request might still temporarily report its state as
+        # Non-Primary.  Do not fail in this case as the promote
+        # operation will loop until the IST finishes or the promote
+        # times out.
+        if [ "$__OCF_ACTION" = "promote" ] && ! ocf_is_true $(is_bootstrap); then
+                ocf_log info "local node <${NODENAME}> is receiving a State Transfer."
+        else
+            ocf_exit_reason "local node <${NODENAME}> is started, but not in primary mode. Unknown state."
+            rc=$OCF_ERR_GENERIC
+        fi
     fi
 
     return $rc
@@ -1030,9 +1024,11 @@ galera_stop()
 
 galera_validate()
 {
-    if ! ocf_is_ms; then
-        ocf_exit_reason "Galera must be configured as a multistate Master/Slave resource."
-        return $OCF_ERR_CONFIGURED
+    if [ "$OCF_CHECK_LEVEL" -eq 10 ]; then
+        if ! ocf_is_ms; then
+            ocf_exit_reason "Galera must be configured as a multistate Master/Slave resource."
+            return $OCF_ERR_CONFIGURED
+        fi
     fi
 
     if [ -z "$OCF_RESKEY_wsrep_cluster_address" ]; then
@@ -1050,6 +1046,7 @@ case "$1" in
         exit $OCF_SUCCESS;;
 esac
 
+[ "$__OCF_ACTION" = "start" ] && OCF_CHECK_LEVEL=10
 galera_validate
 rc=$?
 LSB_STATUS_STOPPED=3
@@ -1107,3 +1104,4 @@ case "$1" in
 esac
 
 # vi:sw=4:ts=4:et:
+
